# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ oldstable, stable ]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
  spell:
    name: "Spell check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          # by default, codespell uses configuration from the .codespellrc
  typos:
    # https://github.com/crate-ci/typos
    # Add exceptions to _typos.toml
    # install and run locally: cargo install typos-cli && typos
    name: typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling of entire workspace
        uses: crate-ci/typos@master